### ISSUE TITLE
Need to use onchange twice....

### ISSUE THREAD

**Issue by babyewok** [vebersol/jQuery-Custom-Forms#2]
I am using this to style my form, but I also want to be able to update certain input values depending on the radio button value once selected - any ideas how I can combine this with your script as it just isn't working!

$(function(){
$(document).ready(function(){
    $("input[name='os0']").live("change", function(){
        if ($(this).val() == "1x30A") {
             $("input.1x30").attr("value", "30");
             $("input.5x30").attr("value", "130");
             $("input.10x30").attr("value", "240");

```
    }
    else if ($(this).val() == "1x30L") {
          $("input.1x30").attr("value", "35");
         $("input.5x30").attr("value", "150");
         $("input.10x30").attr("value", "280");       
    }
}); 
```

});
});

**Comment by vebersol** [comment]
This isn't related to this plugin.
